# Generated by Django 2.1.7 on 2019-05-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='participants',
            field=models.TextField(default=None, help_text='Участники', max_length=300),
            preserve_default=False,
        ),
    ]
