# Generated by Django 2.1.7 on 2019-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20190522_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitting',
            name='max_current_score',
            field=models.IntegerField(default=0, verbose_name='Max Current'),
        ),
    ]
