# Generated by Django 2.1.7 on 2019-05-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answ', models.TextField(blank=True, help_text='Enter the right answer', verbose_name='CorrectAnswer')),
            ],
        ),
    ]
