# Generated by Django 2.1.7 on 2019-05-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0002_essayanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='essayanswer',
            options={'verbose_name': 'EssayAnswer', 'verbose_name_plural': 'EssayAnswers'},
        ),
        migrations.AddField(
            model_name='essayanswer',
            name='question',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='essay.Essay_Question', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
