# Generated by Django 2.1.7 on 2019-05-30 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0004_auto_20190531_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='question',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='essay.Essay_Question', verbose_name='EssayQuestion'),
        ),
    ]
