# Generated by Django 2.1.7 on 2019-05-30 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0005_auto_20190531_0236'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='AnswerID',
            field=models.CharField(default=None, help_text='ID for answer', max_length=100, verbose_name='AnswerID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='essayanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essay.Essay_Question', verbose_name='EssayQuestion'),
        ),
    ]
