# Generated by Django 2.1.7 on 2019-05-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0006_auto_20190531_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='AnswerID',
        ),
    ]
