# Generated by Django 2.1.7 on 2019-05-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0009_remove_essayanswer_answerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='essayanswer',
            name='AnswerID',
            field=models.CharField(default=0, help_text='ID for answer', max_length=100, verbose_name='AnswerID'),
            preserve_default=False,
        ),
    ]
