# Generated by Django 2.1.7 on 2019-05-30 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0010_essayanswer_answerid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='AnswerID',
        ),
    ]
