# Generated by Django 2.1.7 on 2019-05-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0012_essayanswer_answerid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='AnswerID',
            field=models.CharField(default='Null', help_text='ID for answer', max_length=100, verbose_name='AnswerID'),
        ),
    ]
