# Generated by Django 2.1.7 on 2019-05-30 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0013_auto_20190531_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayanswer',
            name='AnswerID',
            field=models.CharField(default=0, help_text='ID for answer', max_length=100, verbose_name='AnswerID'),
        ),
    ]
