# Generated by Django 2.1.7 on 2019-05-30 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0014_auto_20190531_0300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='essayanswer',
            name='AnswerID',
        ),
    ]
