# Generated by Django 2.1.7 on 2019-05-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essay', '0016_essayanswer_answerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay_question',
            name='AnswerID',
            field=models.CharField(default='', help_text='ID for answer', max_length=100, verbose_name='AnswerID'),
        ),
    ]
